---
image: fedora:latest
stages:
  - build_docker
  - build_pdf
  - build_png 
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  
####################################
#   Build Fedora texlive image 
####################################
build_docker:
  image: docker:stable
  stage: build_docker
  services:
    - docker:stable-dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - apk --no-cache add make

  script:
    - make docker_build
    - docker tag resume $IMAGE_TAG
    - docker push $IMAGE_TAG

  after_script:
    - cat build.log

  when: manual
  except:
    - pipelines

####################################
#   Build template 
####################################
.build_artifacts: &build_artifacts
  image: 
    name: $IMAGE_TAG
    entrypoint: []
  services: []

  variables:
    GIT_STRAGEGY: fetch
    GIT_CHECKOUT: "true"

  after_script:
    - cat build.log

####################################
#   Build PDF
####################################
build_pdf:
  <<: *build_artifacts
  stage: build_pdf
  script:
    - rm -f *.pdf
    - make resume.pdf
  artifacts:
    expire_in: '300'
    paths:
      - '*.pdf'

####################################
#   Build PNG 
####################################
build_png:
  <<: *build_artifacts
  stage: build_png
  script:
    - rm *.png
    - make resume.png 
  dependencies: 
    - build_pdf
  artifacts:
    expire_in: '300'
    paths:
      - '*.png'

####################################
#   Deploy
####################################
deploy:
  <<: *build_artifacts
  stage: deploy
  before_script:
    - command -v ssh-agent >/dev/null 2>&1 || ( dnf install -y /usr/bin/ssh-agent )
    - eval $(ssh-agent -s)
    - echo "$GIT_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - git remote set-url origin "git@gitlab.com:${CI_PROJECT_PATH}"
    - git remote -v
    - ssh-add -l
    - git config user.name "Gitlab-CI"
    - git config user.email "git@gitlab.com"
    - git checkout $CI_COMMIT_REF_NAME
    - git add resume.pdf resume-*.png
    - 'git commit -m "Gitlab-CI: Update PNG/PDF files in repository"'
    - git push -u origin $CI_COMMIT_REF_NAME
    - git tag $(date +'%F-%H-%M')
    - git push --tags
  dependencies:
    - build_pdf
    - build_png
  artifacts:
    paths:
      - '*.png'
      - '*.pdf'