---
image: fedora:latest
stages:
  - build_docker
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

####################################
#      Build Fedora texlive image 
####################################
build_docker:
  image: docker:stable
  stage: build_docker
  services:
    - docker:stable-dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - apk --no-cache add make

  script:
    - make docker_build
    - docker tag resume $IMAGE_TAG
    - docker push $IMAGE_TAG

  after_script:
    - cat build.log

  when: manual
  except:
    - pipelines
#####################################


####################################
#      Build Fedora texlive image 
####################################
convert_tex_pdf:
  stage: build
  image: 
    name: $IMAGE_TAG
    entrypoint: []
  services: []

  variables:
    GIT_STRAGEGY: fetch
    GIT_CHECKOUT: "true"

  before_script:
    - git config user.name "Gitlab-CI"
    - git config user.email "git@gitlab.com"
    - make clean # Necessary to remove files make won't build if exists
    
  script:
    - make
    - make git_commit_updates
    - "git commit -m \"Gitlab-CI: Auto update projects files and release artifacts\""
    - git push -u origin $CI_COMMIT_REF_NAME

  after_script:
    - cat build.log

  # only: 
  #   - master
####################################